import { HomeView } from '@/sections/home/view';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function HomePage() {
  return <HomeView />;
}
